### ISSUE TITLE
The API of anaconda.org is providing incorrect information about the latest version.

### ISSUE THREAD

**Issue by akikuno** [conda-forge/feedstock-outputs#75]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When I tried to create a badge using shields for the version of the package registered on conda-forge, an old version (v0.3.1) was reported instead of the latest version (v0.4.1). I inquired about this issue with shields.
https://github.com/badges/shields/issues/10177

Upon inquiry, it was found that the "latest_version" at https://api.anaconda.org/package/conda-forge/wslPath is "0.3.1", and the latest version, which is 0.4.1, is not reflected. Although version "0.4.1" is registered under "versions", why is "latest_version" showing as 0.3.1?

On top of that, in the [wslpath-feedstock](https://github.com/conda-forge/wslpath-feedstock?tab=readme-ov-file#current-release-info), the version is displayed as `0.3.1`. On the other hand, the version displayed on [anaconda.org](https://anaconda.org/conda-forge/wslpath) is `0.4.1`.

I would appreciate any guidance on how to address this issue.

### Installed packages

```shell
None
```

### Environment info

```shell
https://api.anaconda.org/package/conda-forge/wslPath
```

**Comment by jakirkham** [comment]
We have no control over what Anaconda's API shows

Please [raise a `conda/infrastructure` issue]( https://github.com/conda/infrastructure/issues/new )
